In [2]:
import numpy as np
dane = np.load('ex3_data.npy')

In [3]:
#W danych mamy tyle wierszy:
dane.shape[0]

200

In [4]:
braki = np.isnan(dane)
wiersze_braki = np.sum(braki, axis = 1)
indeksy = np.where(wiersze_braki)
indeksy = indeksy[0]

In [5]:
#Wiersze w których mamy brakujące wartości to: 
print(indeksy)

[  1   3   5  13  15  43  50  73  89 123]


In [6]:
#Po odfiltrowaniu odrzucimy zatem tyle wierszy:
len(indeksy)

10

In [7]:
#dane_filtr - dane po odfiltrowaniu kolumn z brakami. Rzeczywiście zostaje 190 wierszy 
indeksy_dobre = np.where(wiersze_braki == 0)
dane_filtr = dane[indeksy_dobre,:][0]
dane_filtr.shape[0]

190

In [8]:
#ile nanów było w każdym wierszu? Pierwsza kolumna - numer wiersza, druga - liczba nanów
na_count = np.vstack((indeksy, wiersze_braki[indeksy]))
print(na_count.transpose())

[[  1   1]
 [  3   1]
 [  5   1]
 [ 13   1]
 [ 15   1]
 [ 43   1]
 [ 50   1]
 [ 73   2]
 [ 89   1]
 [123   1]]


In [9]:
#Ile nanów w każdej kolumnie?

kol_braki = np.sum(braki, axis = 0)
print(kol_braki)

[3 3 4 1]
